import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db/prisma";

const RICH_DEFAULT_CONFIG = (appName: string) => ({
  app: {
    name: appName || "FlowForge CRM App",
    description: "An automated config-driven application generated by FlowForge.",
    language: "en",
    theme: "dark",
    primaryColor: "#00C8E0",
    logo: "",
  },
  auth: {
    methods: ["email"],
    allowSignup: true,
    ui: {
      logo: "",
      primaryColor: "#00C8E0",
      welcomeMessage: "Access your dashboard",
    },
  },
  database: {
    tables: [
      {
        name: "contacts",
        displayName: "Contacts Database",
        fields: [
          { name: "name", type: "string", required: true, label: "Full Name" },
          { name: "email", type: "email", required: true, unique: true, label: "Email Address" },
          { name: "role", type: "string", required: false, default: "User", label: "Job Role" },
          { name: "notes", type: "text", required: false, label: "Additional Notes" },
        ],
      },
      {
        name: "tasks",
        displayName: "Tasks Database",
        fields: [
          { name: "title", type: "string", required: true, label: "Task Title" },
          { name: "priority", type: "string", required: true, default: "Medium", label: "Priority" },
          { name: "completed", type: "boolean", required: false, default: false, label: "Is Completed" },
        ],
      },
    ],
  },
  api: {
    endpoints: [
      { path: "/contacts", method: "GET", table: "contacts", action: "list", auth: false, pagination: true },
      { path: "/contacts", method: "POST", table: "contacts", action: "create", auth: false },
      { path: "/contacts", method: "PUT", table: "contacts", action: "update", auth: false },
      { path: "/contacts", method: "DELETE", table: "contacts", action: "delete", auth: false },
      { path: "/tasks", method: "GET", table: "tasks", action: "list", auth: false, pagination: true },
      { path: "/tasks", method: "POST", table: "tasks", action: "create", auth: false },
      { path: "/tasks", method: "PUT", table: "tasks", action: "update", auth: false },
      { path: "/tasks", method: "DELETE", table: "tasks", action: "delete", auth: false },
    ],
  },
  ui: {
    pages: [
      {
        route: "/",
        title: "Dashboard Home",
        icon: "Home",
        showInNav: true,
        components: [
          {
            id: "hero-stats",
            type: "dashboard",
            table: "contacts",
            config: {
              title: "System Metrics",
              description: "Live overview of contacts and tasks stored in database tables.",
            },
          },
        ],
      },
      {
        route: "/contacts",
        title: "Contacts Registry",
        icon: "Users",
        showInNav: true,
        components: [
          {
            id: "contacts-form",
            type: "form",
            table: "contacts",
            config: {
              title: "Create Contact",
              description: "Fill this form to insert a new row in physical DB contacts table.",
            },
          },
          {
            id: "contacts-table",
            type: "table",
            table: "contacts",
            config: {
              title: "Active Contacts",
              description: "Manage database contacts with sorting, searching, and CSV imports.",
            },
          },
        ],
      },
      {
        route: "/tasks",
        title: "Task Planner",
        icon: "CheckSquare",
        showInNav: true,
        components: [
          {
            id: "tasks-form",
            type: "form",
            table: "tasks",
            config: {
              title: "Plan Task",
              description: "Add items to your live task planner table.",
            },
          },
          {
            id: "tasks-table",
            type: "table",
            table: "tasks",
            config: {
              title: "Active Tasks List",
              description: "Manage scheduled project tasks.",
            },
          },
        ],
      },
    ],
  },
  features: ["csv_import", "notifications", "export_github", "localization"],
  notifications: {
    triggers: [
      { on: "record_created", type: "in_app", message: "Record was added successfully." },
    ],
  },
});

export async function GET(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const userId = (session.user as any).id;
    const apps = await prisma.app.findMany({
      where: { userId },
      orderBy: { updatedAt: "desc" },
    });

    return NextResponse.json(apps);
  } catch (error: any) {
    console.error("[Apps GET Error]:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const userId = (session.user as any).id;
    const body = await req.json().catch(() => ({}));
    const name = body.name || "FlowForge App";

    const defaultAppConfig = RICH_DEFAULT_CONFIG(name);

    const app = await prisma.app.create({
      data: {
        name,
        config: JSON.stringify(defaultAppConfig, null, 2),
        userId,
        isPublished: true,
      },
    });

    return NextResponse.json(app, { status: 201 });
  } catch (error: any) {
    console.error("[Apps POST Error]:", error);
    return NextResponse.json({ error: "Internal Server Error", details: error.message }, { status: 500 });
  }
}
