import { NormalizedConfig } from "./types";

export const DEFAULTS: NormalizedConfig = {
  app: {
    name: "FlowForge App",
    description: "A config-driven application generated by FlowForge",
    language: "en",
    theme: "dark",
    primaryColor: "#00C8E0",
    logo: "",
  },
  auth: {
    methods: ["email"],
    allowSignup: true,
    ui: {
      logo: "",
      primaryColor: "#00C8E0",
      welcomeMessage: "Welcome to FlowForge",
    },
  },
  database: {
    tables: [],
  },
  api: {
    endpoints: [],
  },
  ui: {
    pages: [
      {
        route: "/",
        title: "Home",
        icon: "Home",
        showInNav: true,
        components: [
          {
            id: "welcome-card",
            type: "card",
            table: "",
            config: {
              title: "Welcome to FlowForge",
              description: "Modify the configuration to build your app custom UI components and endpoints.",
            },
          },
        ],
      },
    ],
  },
  features: [],
  notifications: {
    triggers: [],
  },
};
